# Generated by Django 5.2.3 on 2025-06-27 15:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('address', models.CharField(max_length=150)),
                ('address_uz', models.CharField(max_length=150, null=True)),
                ('address_ru', models.CharField(max_length=150, null=True)),
                ('address_en', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('category_uz', models.CharField(max_length=100, null=True)),
                ('category_ru', models.CharField(max_length=100, null=True)),
                ('category_en', models.CharField(max_length=100, null=True)),
                ('price_range', models.CharField(help_text="Arzon, O'rta, Qimmat", max_length=50)),
                ('price_range_uz', models.CharField(help_text="Arzon, O'rta, Qimmat", max_length=50, null=True)),
                ('price_range_ru', models.CharField(help_text="Arzon, O'rta, Qimmat", max_length=50, null=True)),
                ('price_range_en', models.CharField(help_text="Arzon, O'rta, Qimmat", max_length=50, null=True)),
                ('opening_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('closing_time', models.TimeField(blank=True, default=datetime.time(21, 0), null=True)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('location_url', models.URLField(blank=True, null=True)),
                ('tag', models.CharField(max_length=100)),
                ('tag_uz', models.CharField(max_length=100, null=True)),
                ('tag_ru', models.CharField(max_length=100, null=True)),
                ('tag_en', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.regions')),
            ],
        ),
    ]
