# Generated by Django 5.2.3 on 2025-07-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag_ru',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag_uz',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
