# Generated by Django 5.2.3 on 2025-07-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('restaurants', '0002_remove_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.regions'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant'),
        ),
    ]
