# Generated by Django 5.2.3 on 2025-07-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
