# Generated by Django 5.2.3 on 2025-07-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_address_alter_restaurant_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
