# Generated by Django 5.2.3 on 2025-07-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location_url',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number_2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tag_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tag_uz',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
    ]
