# Generated by Django 5.2.3 on 2025-07-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_location_url_hotel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
