# Generated by Django 5.2.3 on 2025-07-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
