# Generated by Django 5.2.3 on 2025-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='address_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='place_type_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='place_type_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='place_type_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
