# Generated by Django 5.2.3 on 2025-07-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='location_url',
        ),
        migrations.AddField(
            model_name='travel',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='regions',
            field=models.ManyToManyField(related_name='travels', to='hotels.regions'),
        ),
    ]
