# Generated by Django 5.2.3 on 2025-06-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travel_address_en_travel_address_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='price',
            new_name='ticket_price',
        ),
    ]
