# Generated by Django 5.2.3 on 2025-07-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_travel_location_url_travel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='place_type',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='place_type_en',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='place_type_ru',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='place_type_uz',
        ),
    ]
