# Generated by Django 5.2.3 on 2025-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_remove_travel_place_type_remove_travel_place_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='travel',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='address_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='address_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
